<?php

namespace ApartmentBundle\Repository;


/**
 * ApartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList(int $limit = 10, int $offset = 0)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $q  = $qb->select(['ap'])
            ->from('ApartmentBundle:Apartment', 'ap')
            ->orderBy('ap.postedAt', 'DESC')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery();

        return $q->getResult();
    }

    public function getTotal()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $q  = $qb->select('COUNT(ap)')
            ->from('ApartmentBundle:Apartment', 'ap')
            ->getQuery();

        return intval($q->getSingleScalarResult());
    }
}
