<?php

namespace ApartmentBundle\Repository;


/**
 * ApartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActiveApartments()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $q  = $qb->select(['ap'])
            ->from('ApartmentBundle:Apartment', 'ap')
            ->where(
                $qb->expr()->eq('ap.status', true)
            )
            ->orderBy('ap.postedAt', 'DESC')
            ->getQuery();

        return $q->getResult();
    }
}
